### ISSUE TITLE
tashkeel placement and spacing bugs 

### ISSUE THREAD

**Issue by Gue3bara** [zeynepakay/theruqahproject#18]
The following are sample of random tashkeel marks placement bugs i noticed 
between the anchor being too close to baseline to overlapping other following glyphs 
<img width="187" alt="screenshot 2017-06-29 01 09 15" src="https://user-images.githubusercontent.com/12478169/27664505-342f8744-5c68-11e7-8eeb-270428b0b6b3.png">
<img width="209" alt="screenshot 2017-06-29 01 08 44" src="https://user-images.githubusercontent.com/12478169/27664506-3432f9a6-5c68-11e7-87e3-5721c67c2fb9.png">
<img width="118" alt="screenshot 2017-06-29 01 08 36" src="https://user-images.githubusercontent.com/12478169/27664507-3438c5de-5c68-11e7-95ce-b9dd27fb83e9.png">
<img width="258" alt="screenshot 2017-06-29 01 08 30" src="https://user-images.githubusercontent.com/12478169/27664508-343dac48-5c68-11e7-8e2a-cad24d56781a.png">
<img width="202" alt="screenshot 2017-06-29 01 08 20" src="https://user-images.githubusercontent.com/12478169/27664509-345f170c-5c68-11e7-8b3c-df22e67a4fe1.png">
<img width="281" alt="screenshot 2017-06-29 01 08 09" src="https://user-images.githubusercontent.com/12478169/27664510-34638346-5c68-11e7-9578-93db02216b0c.png">
<img width="550" alt="screenshot 2017-06-29 01 07 49" src="https://user-images.githubusercontent.com/12478169/27664511-346825fe-5c68-11e7-9ad5-f7613cf6110e.png">
<img width="283" alt="screenshot 2017-06-29 01 07 34" src="https://user-images.githubusercontent.com/12478169/27664512-346a410e-5c68-11e7-853b-d335386f5060.png">
<img width="267" alt="screenshot 2017-06-29 01 07 05" src="https://user-images.githubusercontent.com/12478169/27664513-3482cd96-5c68-11e7-8dca-0ca1412d4179.png">
<img width="283" alt="screenshot 2017-06-29 01 06 57" src="https://user-images.githubusercontent.com/12478169/27664514-348706ea-5c68-11e7-9142-436dae31cfbc.png">
<img width="332" alt="screenshot 2017-06-29 01 06 42" src="https://user-images.githubusercontent.com/12478169/27664515-348c8052-5c68-11e7-951f-3d6476788772.png">
<img width="441" alt="screenshot 2017-06-29 01 05 14" src="https://user-images.githubusercontent.com/12478169/27664516-34942f28-5c68-11e7-851c-e39c5d2d1fe2.png">

**Comment by Gue3bara** [comment]
Im working on a fix for the tashkeel positioning bugs and here i needed to make a list of new ligatures for all the glyphs with tashkeel marks overlapping with the kaf 
this is a sample
Before
<img width="454" alt="screenshot 2017-07-01 15 56 28" src="https://user-images.githubusercontent.com/12478169/27762621-2477cf90-5e76-11e7-9c6a-d7200cedbb2c.png">
After
<img width="447" alt="screenshot 2017-07-01 15 56 33" src="https://user-images.githubusercontent.com/12478169/27762623-2b8e9d22-5e76-11e7-8f85-51fdc9fac372.png">

**Comment by zeynepakay** [comment]
I was struggling with this myself (the clash of the kaf 'flag' and the the diacritics over the preceding letter)  and couldn't figure out even with contextual kerning. The only "workaround" I came up with was diacritic position adjustment in InDesign CC ME. I think creating ligatures and moving the anchors is a great idea!
