### ISSUE TITLE
Nuqta size related discussion

### ISSUE THREAD

**Issue by Gue3bara** [zeynepakay/theruqahproject#19]
i noticed that the single nuqta is relatively too small compared to the baseline thickness
<img width="276" alt="screenshot 2017-06-29 01 21 12" src="https://user-images.githubusercontent.com/12478169/27664702-518f8f7c-5c69-11e7-9152-0a46ce2a209e.png">
, not only because for classic ruqaa uses the nuqta as the measurement unit for the letters vertical and horizontal measurements but it's also confusing with the fatha/kasra in some situations 
<img width="263" alt="screenshot 2017-06-29 01 20 55" src="https://user-images.githubusercontent.com/12478169/27664703-51960ef6-5c69-11e7-8f11-9002f2162029.png">

the following is the fix im proposing 
<img width="350" alt="screenshot 2017-06-29 01 47 16" src="https://user-images.githubusercontent.com/12478169/27665361-05d78f04-5c6d-11e7-89e8-7aa7082bca23.png">
**BEFORE**
<img width="350" alt="screenshot 2017-06-29 01 46 44" src="https://user-images.githubusercontent.com/12478169/27665359-ff8ce8ec-5c6c-11e7-8d24-23de7618e199.png">
**AFTER**

**Comment by zeynepakay** [comment]
Being that this design is derived from lettering -not calligraphy or writing- where they take liberties with sizes and shapes of dots, I'm ok with them not matching baseline thickness. If it does cause readability issues with fatha/kasra marks, then it's ok to enlarge them, however, perhaps not to the extent as shown in 'after.' Perhaps there is a middle point or something slightly smaller than your suggestion so the typeface doesn't lose its personality?
