### ISSUE TITLE
excess space after reh

### ISSUE THREAD

**Issue by Gue3bara** [zeynepakay/theruqahproject#21]
I noticed Reh has spacing problem with following glyph is that intended? 
do you think it needs fix to reduce this space?
<img width="480" alt="screenshot 2017-06-29 01 09 04" src="https://user-images.githubusercontent.com/12478169/27713909-2e605ca0-5d2e-11e7-9e36-f1d2126e2a30.png">
<img width="414" alt="screenshot 2017-06-29 01 08 03" src="https://user-images.githubusercontent.com/12478169/27713910-2e66c6b2-5d2e-11e7-9343-e13858d9d194.png">
<img width="480" alt="22" src="https://user-images.githubusercontent.com/12478169/27713980-94391e40-5d2e-11e7-909c-86f297cefa2c.png">

**Comment by Gue3bara** [comment]
**BEFORE**
<img width="824" alt="screenshot 2017-06-30 01 02 04" src="https://user-images.githubusercontent.com/12478169/27714202-c62ac632-5d2f-11e7-809f-11fd3e80ba9e.png">

**AFTER**
<img width="786" alt="screenshot 2017-06-30 01 01 25" src="https://user-images.githubusercontent.com/12478169/27714211-cc612172-5d2f-11e7-8ba5-4e28e87727c0.png">

**Comment by zeynepakay** [comment]
great, the fix seems to work well
