### ISSUE TITLE
connecting overlap shift

### ISSUE THREAD

**Issue by Gue3bara** [zeynepakay/theruqahproject#22]
with some glyphs the connecting overlap is shifted up by a point 
<img width="920" alt="screenshot 2017-06-30 01 22 28" src="https://user-images.githubusercontent.com/12478169/27714680-c91d7300-5d32-11e7-9b31-11f7a2a0f600.png">
<img width="263" alt="screenshot 2017-06-30 01 22 08" src="https://user-images.githubusercontent.com/12478169/27714682-ca6bf7d6-5d32-11e7-904d-6002d06385bc.png">

**Comment by zeynepakay** [comment]
yep, should be fixed
