### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by davelab6** [zeynepakay/theruqahproject#4]
To delete the empty master branch:

``` sh
git branch -d master;
git push origin :master;
```

**Comment by zeynepakay** [comment]
Hi, didn't understand this?

**Comment by davelab6** [comment]
The monospace text in grey background is Terminal commands to run inside the project repository's directory to delete the master branch locally, and then delete it from Github's servers. 

However, there are now 4 branches in the repo, but ideally there should only be 1 main development branch. If you have trouble merging the branches so none are ahead of yours, I can help (perhaps via hangout)

**Comment by davelab6** [comment]
@zeynepakay said offline,

> The additional branches happened because something irrevocable happened to the file and I had to checkout a previous commit and continue on that branch.

So I will merge the branches taking care of this in my fork, and detail how I did it

**Comment by davelab6** [comment]
The `pr/3` branch doesn't have anything useful any more and can be deleted like this:

```
git checkout gh-pages ; # make sure you are on the gh-pages branch
git branch -D pr/3 ; # remove it from this local repo
git push origin :pr/3 ; # remove it on github.com servers repo
```

The `master` branch has just 2 commits not in the `Rukiye` branch, which from their commit messages seem to be mistakes. You can see the comparison of the two here:

https://github.com/zeynepakay/theruqahproject/compare/Rukiye...master

So again we can just remove that branch:

```
git checkout gh-pages ; # make sure you are on the gh-pages branch
git branch -D master ; # remove it from this local repo
git push origin :master ; # remove it on github.com servers repo
```

The `Rukiye` branch can be merged like this:

```
git checkout gh-pages ; # make sure you are on the gh-pages branch
git merge Rukiye; # merge that branch
git push; # push the merge to the github server
git branch -d Rukiye ; # remove it from this local repo
git push origin :Rukiye ; # remove it on github.com servers repo
```

**Comment by davelab6** [comment]
Thanks!
