### ISSUE TITLE
Directory and file layout

### ISSUE THREAD

**Issue by davelab6** [zeynepakay/theruqahproject#5]
The layout of the directories and files could be improved. 

I've put up https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md which has tips on directory and file layout. 

Please take a look (you can probably skip the first section about tools) and let me know if anything is unclear :)

**Comment by davelab6** [comment]
In particular, I'd like to get the project description for the www.google.com/fonts directory sorted out this week :D

**Comment by davelab6** [comment]
Any news on the project description?

**Comment by zeynepakay** [comment]
Hi,

Just updated the Readme file with a new description and a sample image using the name of the font. Is that alright?

I had a couple of questions, upon going through the guide:

1) Do the highest/lowest glyph limits apply to Arabic as well? I’m within bounds on the ascender level, but my descender is at -455. 

2) I don’t have full Latin 5 / Vietnamese support. Do I need to have that for this release?

3) Same question for figure sets. I only have two, standard and old style.

Also, I should wait for you to merge the branches before I rename the files and the repo, right?

I’m updating my test documents for each script. I have to compile a lot of bits and pieces. Should be done within the day.

Best,

Z.

**Comment by davelab6** [comment]
> 1) Do the highest/lowest glyph limits apply to Arabic as well? I’m within bounds on the ascender level, but my descender is at -455.

That's fine! Actually Arabic fonts tend to need to break the rules on this a bit, otherwise they can be too small. Does it look okay on www.impallari.com/testing compared to say Open Sans and Amiri?

> 2) I don’t have full Latin 5 / Vietnamese support. Do I need to have that for this release?

No! I'm pretty sure the minimum is Adobe Latin 3 for this release

> 3) Same question for figure sets. I only have two, standard and old style.

Okay - the other 2 numeral styles are the same glyph shapes but with proportional or tabular (monospace) spacing, so it is less than an hour to add them. There are also good GlyphsApp.com tutorials on how to get the OT code working. 

> Also, I should wait for you to merge the branches before I rename the files and the repo, right?

Yes, I'll tend to this now

**Comment by davelab6** [comment]
> Just updated the Readme file with a new description and a sample image using the name of the font. Is that alright?

Yes, this is good - although I'd like more detail about the design, its inspiration, interesting design details in certain glyphs, etc

**Comment by davelab6** [comment]
@zeynepakay all done here? :)
