### ISSUE TITLE
Improve beh forms

### ISSUE THREAD

**Issue by davelab6** [zeynepakay/theruqahproject#9]
- [x] The beh forms could switch up when there is more than one in a row when there are vowel marks present, this is a bug in the CA feature lookup

**Comment by zeynepakay** [comment]
The beh forms _do_ switch up when there are more than one in a row, but not when there are also diacritics present. This is the bug in the CA feature.

**Comment by davelab6** [comment]
I've edited the issue text, please feel fee to edit as needed :)

**Comment by davelab6** [comment]
@zeynepakay any news on this? :)

**Comment by zeynepakay** [comment]
Still working on it. Should have something this week. :)

**Comment by davelab6** [comment]
Great :)

On 4 April 2016 at 07:19, zeynepakay notifications@github.com wrote:

> Still working on it. Should have something this week. :)
> 
> > On 30 Mar 2016, at 16:18, Dave Crossland notifications@github.com
> > wrote:
> > 
> > @zeynepakay https://github.com/zeynepakay any news on this? :)
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub <
> > https://github.com/zeynepakay/Rakkas/issues/9#issuecomment-203484630>
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/zeynepakay/Rakkas/issues/9#issuecomment-205249274

## 

Cheers
Dave

**Comment by zeynepakay** [comment]
Solved! Adding the class of diacritics (and the stylistic alternate diacritics) to the context in the lookup seems to work.
